// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/arcticescapebk.tga
gfx/env/arcticescapedn.tga
gfx/env/arcticescapeft.tga
gfx/env/arcticescapelf.tga
gfx/env/arcticescapert.tga
gfx/env/arcticescapeup.tga
models/arcticescape/ac_large.mdl
models/arcticescape/airconditioner.mdl
models/arcticescape/antenna.mdl
models/arcticescape/barrelgibs.mdl
models/arcticescape/barrels.mdl
models/arcticescape/boat_metal.mdl
models/arcticescape/coke_bag.mdl
models/arcticescape/coke_box.mdl
models/arcticescape/crate.mdl
models/arcticescape/crategibs.mdl
models/arcticescape/deadguy_arctic.mdl
models/arcticescape/desk.mdl
models/arcticescape/electrical_box.mdl
models/arcticescape/fence.mdl
models/arcticescape/filecabinet.mdl
models/arcticescape/generator.mdl
models/arcticescape/keycard.mdl
models/arcticescape/lamp.mdl
models/arcticescape/lifeboat.mdl
models/arcticescape/light.mdl
models/arcticescape/oxygen.mdl
models/arcticescape/padlock.mdl
models/arcticescape/radar.mdl
models/arcticescape/radio.mdl
models/arcticescape/rib.mdl
models/arcticescape/satellite_dish.mdl
models/arcticescape/ship_bed.mdl
models/arcticescape/ship_bridgechair.mdl
models/arcticescape/ship_bridgewheel.mdl
models/arcticescape/ship_galley.mdl
models/arcticescape/sink.mdl
models/arcticescape/snowcat.mdl
models/arcticescape/toilet.mdl
models/arcticescape/toolbox.mdl
models/arcticescape/toolchest.mdl
models/arcticescape/ventgibs.mdl
sound/arcticescape/secret.mp3
sound/arcticescape/water.wav
sprites/arcticescape/secret.spr
sprites/arcticescape/wrong_way.spr
