gfx/env/kamijungle envmap readme.txt
gfx/env/kamijunglebk.bmp
gfx/env/kamijungledn.bmp
gfx/env/kamijungleft.bmp
gfx/env/kamijunglelf.bmp
gfx/env/kamijunglert.bmp
gfx/env/kamijungleup.bmp
maps/artifact.cfg
maps/artifact_motd.txt
models/artifact/baboon2.mdl
models/artifact/key1.mdl
models/artifact/key2.mdl
models/artifact/key3.mdl
models/artifact/key3a.mdl
models/artifact/sunsceptre.mdl
sound/artifact/artifactvoxfull2.wav
sound/artifact/cave_ambience.wav
sound/artifact/endwav1.wav
sound/artifact/heli1.wav
sound/artifact/jungle_ambience.wav
sound/artifact/jungle_drums.wav
sound/artifact/jungle_river.wav
sound/artifact/ruins_pipes.wav
sound/artifact/stone_rumble.wav
sprites/adamr/pointers/pointer-shortcut.spr
sprites/artifact/artifactspr1.spr
sprites/artifact/artifactspr2.spr
