////////////////////////////////////////////////////////////////////////
// gausslabbeta2.res - .RES File created with RJ's RES Generator v1.1 //
// DO NOT EDIT THIS FILE                                              //
// RJ's RES Generator is made by RJ8722                               //
// For more info go to http://www.rjscodingrealm.com/resgen.php       //
////////////////////////////////////////////////////////////////////////

// Map downloaded from a Peany.net Server - http://www.peany.net/

// .res entries (12):
maps/gausslabbeta2.cfg
maps/gausslabbeta2.res
maps/gausslabbeta2.txt
maps/gausslabbeta2_motd.txt
maps/gausslabbeta2_readme.txt
models/turr/p_keyboard.mdl
models/turr/v_keyboard.mdl
models/turr/w_keyboard.mdl
sound/gausslabsbeta/keyboard.txt
sound/misc/secret.wav
sound/omg/picard.wav
sound/tur/dylan.wav