// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/jurassicbk.tga
gfx/env/jurassicdn.tga
gfx/env/jurassicft.tga
gfx/env/jurassiclf.tga
gfx/env/jurassicrt.tga
gfx/env/jurassicup.tga
models/jurassicpark/airconditioner.mdl
models/jurassicpark/bush_evergreen.mdl
models/jurassicpark/bush_fern_small.mdl
models/jurassicpark/bush_japan_fern_01.mdl
models/jurassicpark/bush_shrubv01.mdl
models/jurassicpark/chopper2.mdl
models/jurassicpark/keycard.mdl
models/jurassicpark/lab_machine.mdl
models/jurassicpark/lab_microscope.mdl
models/jurassicpark/lab_oscilliscope.mdl
models/jurassicpark/lab_scale.mdl
models/jurassicpark/lab_table.mdl
models/jurassicpark/oxygen.mdl
models/jurassicpark/pentarun.mdl
models/jurassicpark/raptorbox.mdl
models/jurassicpark/raptorhiss.mdl
models/jurassicpark/raptoridle.mdl
models/jurassicpark/raptorrun.mdl
models/jurassicpark/rib.mdl
models/jurassicpark/scaffold.mdl
models/jurassicpark/scaffold_short.mdl
models/jurassicpark/tree_broken.mdl
models/jurassicpark/tree_greyv1.mdl
models/jurassicpark/tree_gshaded.mdl
models/jurassicpark/tree_japan_round.mdl
models/jurassicpark/tree_jungle01.mdl
models/jurassicpark/tree_jungle02.mdl
models/jurassicpark/tree_jungle_07.mdl
models/jurassicpark/tree_junglev03.mdl
models/jurassicpark/trex.mdl
models/jurassicpark/trexbite.mdl
models/jurassicpark/trexdie.mdl
models/jurassicpark/trexidle.mdl
sound/jurassicpark/credits.wav
sound/jurassicpark/ends.wav
sound/jurassicpark/finale.wav
sound/jurassicpark/gun.wav
sound/jurassicpark/jungle.wav
sound/jurassicpark/raptor.wav
sound/jurassicpark/raptor2.wav
sound/jurassicpark/trex.wav
sound/jurassicpark/water.wav
sprites/jurassicpark/smoke.spr
