gfx/env/planet3cBK.bmp
gfx/env/planet3cBK.tga
gfx/env/planet3cDN.bmp
gfx/env/planet3cDN.tga
gfx/env/planet3cFT.bmp
gfx/env/planet3cFT.tga
gfx/env/planet3cLF.bmp
gfx/env/planet3cLF.tga
gfx/env/planet3cRT.bmp
gfx/env/planet3cRT.tga
gfx/env/planet3cUP.bmp
gfx/env/planet3cUP.tga
maps/planet3c_r.cfg
maps/planet3c_r_motd.txt
models/planet3c/bluecrystal.mdl
models/planet3c/indigocrystal.mdl
models/planet3c/orangecrystal.mdl
models/planet3c/p3cgrunt1.mdl
models/planet3c/p3cgrunt1T.mdl
models/planet3c/p3cgrunt2.mdl
models/planet3c/p3cgrunt2T.mdl
models/planet3c/p3cmedic.mdl
models/planet3c/redcrystal.mdl
models/planet3c/sittingman.mdl
models/planet3c/sittingman01.mdl
models/planet3c/violetcrystal.mdl
models/planet3c/yellowcrystal.mdl
sound/planet3c/asteroid.ogg
sound/planet3c/carcrash.ogg
sound/planet3c/cardoor.ogg
sound/planet3c/carrun.ogg
sound/planet3c/evacuationvox.ogg
sound/planet3c/finalvox.ogg
sound/planet3c/hotelambience.ogg
sound/planet3c/morning1.ogg
sound/planet3c/morning2.ogg
sound/planet3c/morning3.ogg
sound/planet3c/newsvox.ogg
sound/planet3c/p3ccurrent.ogg
sound/planet3c/p3cmayday.ogg
sound/planet3c/p3crain.ogg
sound/planet3c/p3cthunder.ogg
sound/planet3c/robotvox1.ogg
sound/planet3c/robotvox2.ogg
sound/planet3c/robotvox3.ogg
sound/planet3c/robotvox5.ogg
sound/planet3c/secretwavintro.ogg
sound/planet3c/secretwavmain.ogg
sound/planet3c/shiptakeoff.ogg
sound/planet3c/trainvoxfull.ogg
sound/planet3c/tvvox.ogg
sound/planet3c/workervox1.ogg
sound/planet3c/workervox2.ogg
sprites/adamr/pointers/pointer-shortcut.spr
