// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

gfx/env/csblueskybk.tga
gfx/env/csblueskydn.tga
gfx/env/csblueskyft.tga
gfx/env/csblueskylf.tga
gfx/env/csblueskyrt.tga
gfx/env/csblueskyup.tga
models/egyptesc/ownage.mdl
models/merryxmas/xms_cow.mdl
models/skillrun3/falco.mdl
models/skillrun3/hat1.mdl
models/skillrun3/hat10.mdl
models/skillrun3/hat2.mdl
models/skillrun3/hat3.mdl
models/skillrun3/hat4.mdl
models/skillrun3/hat5.mdl
models/skillrun3/hat6.mdl
models/skillrun3/hat7.mdl
models/skillrun3/hat8.mdl
models/skillrun3/hat9.mdl
models/snstrafe/teleporter.mdl
models/snstrafe/whchair2.mdl
sound/kristine/cluck2.wav
sound/skillrun3/amb_caveentrance.wav
sound/skillrun3/amb_colorgeyser.wav
sound/skillrun3/amb_creaking.wav
sound/skillrun3/amb_crystalcave.wav
sound/skillrun3/amb_crystalglimm.wav
sound/skillrun3/amb_darkcave.wav
sound/skillrun3/amb_desertcrickets.wav
sound/skillrun3/amb_drips.wav
sound/skillrun3/amb_dryair.wav
sound/skillrun3/amb_flies.wav
sound/skillrun3/amb_hawk.wav
sound/skillrun3/amb_lake.wav
sound/skillrun3/amb_lavacave.wav
sound/skillrun3/amb_lavafall.wav
sound/skillrun3/amb_lavapool.wav
sound/skillrun3/amb_lighthumm.wav
sound/skillrun3/amb_medwfall.wav
sound/skillrun3/amb_mushydungeon.wav
sound/skillrun3/amb_mushyentrance.wav
sound/skillrun3/amb_poolindoor.wav
sound/skillrun3/amb_shaft.wav
sound/skillrun3/amb_smallwfall.wav
sound/skillrun3/amb_snake.wav
sound/skillrun3/amb_solocricket.wav
sound/skillrun3/amb_springcave.wav
sound/skillrun3/amb_springvalley.wav
sound/skillrun3/amb_springwoods.wav
sound/skillrun3/amb_summerbirds.wav
sound/skillrun3/amb_summeryard.wav
sound/skillrun3/amb_teleport.wav
sound/skillrun3/amb_toads.wav
sound/skillrun3/amb_volcaneurption.wav
sound/skillrun3/amb_waterpool.wav
sound/skillrun3/amb_wildwestmine.wav
sound/skillrun3/amb_windydesert.wav
sound/skillrun3/event_laddercreak1.wav
sound/skillrun3/event_laddercreak2.wav
sound/skillrun3/falcosroom.ogg
sound/skillrun3/item_button.wav
sound/skillrun3/item_healing.wav
sound/skillrun3/item_secret.wav
sound/skillrun3/outro1.ogg
sound/skillrun3/outro2.ogg
sound/skillrun3/outro3.ogg
sound/skillrun3/skillrun3_intro.ogg
sound/snstrafe/rs_bh_pickup.wav
sprites/adamr/observer_button.spr
sprites/polarcomplex/bigfade.spr
sprites/skillrun3/flatglow.spr
sprites/skillrun3/glowfoggydark.spr
sprites/skillrun3/glowyellow.spr
sprites/skillrun3/greendustfloat.spr
sprites/skillrun3/lavafall.spr
sprites/skillrun3/moth_flies.spr
sprites/skillrun3/mushylight.spr
sprites/skillrun3/secretflower.spr
sprites/skillrun3/teleport.spr
sprites/skillrun3/weapon_momslipper.txt
sprites/snstrafe/bling.spr
sprites/snstrafe/flames.spr
