// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/muzzle_sentry_uzi.txt
gfx/env/snowsoldierbk.tga
gfx/env/snowsoldierdn.tga
gfx/env/snowsoldierft.tga
gfx/env/snowsoldierlf.tga
gfx/env/snowsoldierrt.tga
gfx/env/snowsoldierup.tga
maps/soldier_mat.txt
models/ecsc/p_flamethrower_r.mdl
models/ecsc/v_flamethrower.mdl
models/ecsc/w_flamethrower.mdl
models/isc/sdx/p_welder.mdl
models/isc/sdx/v_welder.mdl
models/isc/sdx/w_welder.mdl
models/snk_ema/soldier/hassassin.mdl
models/snk_ema/soldier/hgrunt.mdl
models/snk_ema/soldier/p_357.mdl
models/snk_ema/soldier/p_9mmAR.mdl
models/snk_ema/soldier/p_crowbar.mdl
models/snk_ema/soldier/p_grenade.mdl
models/snk_ema/soldier/p_machete_test.mdl
models/snk_ema/soldier/p_p228.mdl
models/snk_ema/soldier/p_shotgun.mdl
models/snk_ema/soldier/parachute.mdl
models/snk_ema/soldier/sentry.mdl
models/snk_ema/soldier/snow_bush.mdl
models/snk_ema/soldier/snow_tree.mdl
models/snk_ema/soldier/v_357.mdl
models/snk_ema/soldier/v_9mmAR.mdl
models/snk_ema/soldier/v_btorch.mdl
models/snk_ema/soldier/v_crowbar.mdl
models/snk_ema/soldier/v_flamethrower.mdl
models/snk_ema/soldier/v_grenade.mdl
models/snk_ema/soldier/v_machete_test.mdl
models/snk_ema/soldier/v_p228.mdl
models/snk_ema/soldier/v_satchel.mdl
models/snk_ema/soldier/v_satchel_radio.mdl
models/snk_ema/soldier/v_shotgun.mdl
models/snk_ema/soldier/v_syringegun.mdl
models/snk_ema/soldier/v_tripmine.mdl
models/snk_ema/soldier/w_357.mdl
models/snk_ema/soldier/w_357ammobox.mdl
models/snk_ema/soldier/w_9mmAR.mdl
models/snk_ema/soldier/w_grenade.mdl
models/snk_ema/soldier/w_machete.mdl
models/snk_ema/soldier/w_p228.mdl
models/snk_ema/soldier/w_shotgun.mdl
sound/ambience/eagle.wav
sound/ambience/fire.wav
sound/debris/glass.wav
sound/hgruntop4-old/alien1.wav
sound/hgruntop4-old/alien2.wav
sound/hgruntop4-old/alien3.wav
sound/hgruntop4-old/alien4.wav
sound/hgruntop4-old/answer1.wav
sound/hgruntop4-old/answer2.wav
sound/hgruntop4-old/answer3.wav
sound/hgruntop4-old/answer4.wav
sound/hgruntop4-old/answer5.wav
sound/hgruntop4-old/answer6.wav
sound/hgruntop4-old/answer7.wav
sound/hgruntop4-old/charge1.wav
sound/hgruntop4-old/charge2.wav
sound/hgruntop4-old/charge3.wav
sound/hgruntop4-old/charge4.wav
sound/hgruntop4-old/check1.wav
sound/hgruntop4-old/check2.wav
sound/hgruntop4-old/check3.wav
sound/hgruntop4-old/check4.wav
sound/hgruntop4-old/check5.wav
sound/hgruntop4-old/check6.wav
sound/hgruntop4-old/check7.wav
sound/hgruntop4-old/check8.wav
sound/hgruntop4-old/clear1.wav
sound/hgruntop4-old/clear10.wav
sound/hgruntop4-old/clear11.wav
sound/hgruntop4-old/clear12.wav
sound/hgruntop4-old/clear2.wav
sound/hgruntop4-old/clear3.wav
sound/hgruntop4-old/clear4.wav
sound/hgruntop4-old/clear5.wav
sound/hgruntop4-old/clear6.wav
sound/hgruntop4-old/clear7.wav
sound/hgruntop4-old/clear8.wav
sound/hgruntop4-old/clear9.wav
sound/hgruntop4-old/cover1.wav
sound/hgruntop4-old/cover2.wav
sound/hgruntop4-old/cover3.wav
sound/hgruntop4-old/cover4.wav
sound/hgruntop4-old/cover5.wav
sound/hgruntop4-old/cover6.wav
sound/hgruntop4-old/gr_die1.wav
sound/hgruntop4-old/gr_die2.wav
sound/hgruntop4-old/gr_die3.wav
sound/hgruntop4-old/gr_pain1.wav
sound/hgruntop4-old/gr_pain2.wav
sound/hgruntop4-old/gr_pain3.wav
sound/hgruntop4-old/gr_pain4.wav
sound/hgruntop4-old/gr_pain5.wav
sound/hgruntop4-old/gren1.wav
sound/hgruntop4-old/gren2.wav
sound/hgruntop4-old/gren3.wav
sound/hgruntop4-old/gren4.wav
sound/hgruntop4-old/gren5.wav
sound/hgruntop4-old/gren6.wav
sound/hgruntop4-old/idle1.wav
sound/hgruntop4-old/idle2.wav
sound/hgruntop4-old/idle3.wav
sound/hgruntop4-old/player1.wav
sound/hgruntop4-old/player2.wav
sound/hgruntop4-old/player3.wav
sound/hgruntop4-old/player4.wav
sound/hgruntop4-old/player5.wav
sound/hgruntop4-old/player6.wav
sound/hgruntop4-old/player7.wav
sound/hgruntop4-old/quest1.wav
sound/hgruntop4-old/quest10.wav
sound/hgruntop4-old/quest11.wav
sound/hgruntop4-old/quest12.wav
sound/hgruntop4-old/quest2.wav
sound/hgruntop4-old/quest3.wav
sound/hgruntop4-old/quest4.wav
sound/hgruntop4-old/quest5.wav
sound/hgruntop4-old/quest6.wav
sound/hgruntop4-old/quest7.wav
sound/hgruntop4-old/quest8.wav
sound/hgruntop4-old/quest9.wav
sound/hgruntop4-old/sonofabitch.wav
sound/hgruntop4-old/taunt1.wav
sound/hgruntop4-old/taunt2.wav
sound/hgruntop4-old/taunt3.wav
sound/hgruntop4-old/taunt4.wav
sound/hgruntop4-old/taunt5.wav
sound/hgruntop4-old/taunt6.wav
sound/hgruntop4-old/throw1.wav
sound/hgruntop4-old/throw2.wav
sound/hgruntop4-old/throw3.wav
sound/hgruntop4-old/throw4.wav
sound/isc/sdx/fire_off.ogg
sound/isc/sdx/fire_run.ogg
sound/isc/sdx/fire_startup.ogg
sound/snk_ema/hecusleveless/misc/cj-mitrc15.ogg
sound/snk_ema/hecusleveless/misc/weapondrop1.wav
sound/snk_ema/hecusleveless/misc/weapondrop2.wav
sound/snk_ema/hevhecu/flashlight1.wav
sound/snk_ema/madness/mp5k_fire_hlc.wav
sound/snk_ema/sand/ammolow_inv.wav
sound/snk_ema/sand/bandage.wav
sound/snk_ema/sand/critical_inv01.wav
sound/snk_ema/sand/critical_res01.wav
sound/snk_ema/sand/critical_res02.wav
sound/snk_ema/sand/critical_res03.wav
sound/snk_ema/sand/death_scream01.wav
sound/snk_ema/sand/death_scream02.wav
sound/snk_ema/sand/death_scream03.wav
sound/snk_ema/sand/death_scream05.wav
sound/snk_ema/sand/flashed_res03.wav
sound/snk_ema/sand/medic_inv.wav
sound/snk_ema/sand/wounded6.wav
sound/snk_ema/sand/wounded9.wav
sound/snk_ema/soldier/357_shot1.wav
sound/snk_ema/soldier/ammopickup2.wav
sound/snk_ema/soldier/bell1.wav
sound/snk_ema/soldier/biggun2.wav
sound/snk_ema/soldier/blip1.wav
sound/snk_ema/soldier/blip2.wav
sound/snk_ema/soldier/button1.wav
sound/snk_ema/soldier/button10.wav
sound/snk_ema/soldier/button11.wav
sound/snk_ema/soldier/button2.wav
sound/snk_ema/soldier/button3.wav
sound/snk_ema/soldier/button4.wav
sound/snk_ema/soldier/button5.wav
sound/snk_ema/soldier/button6.wav
sound/snk_ema/soldier/button7.wav
sound/snk_ema/soldier/button8.wav
sound/snk_ema/soldier/button9.wav
sound/snk_ema/soldier/crow.wav
sound/snk_ema/soldier/de_clipin.wav
sound/snk_ema/soldier/de_clipout.wav
sound/snk_ema/soldier/de_slidepull.wav
sound/snk_ema/soldier/de_sliderelease.wav
sound/snk_ema/soldier/deagle_1.wav
sound/snk_ema/soldier/draw.wav
sound/snk_ema/soldier/envwind.wav
sound/snk_ema/soldier/gunpickup2.wav
sound/snk_ema/soldier/heli.wav
sound/snk_ema/soldier/hks1.wav
sound/snk_ema/soldier/jet.wav
sound/snk_ema/soldier/knife_hit1.wav
sound/snk_ema/soldier/knife_hitwall1.wav
sound/snk_ema/soldier/knife_slash1.wav
sound/snk_ema/soldier/m60-1.wav
sound/snk_ema/soldier/machete_deploy1.wav
sound/snk_ema/soldier/machete_hit1.wav
sound/snk_ema/soldier/machete_hit2.wav
sound/snk_ema/soldier/machete_hit3.wav
sound/snk_ema/soldier/machete_hit4.wav
sound/snk_ema/soldier/machete_hitwall1.wav
sound/snk_ema/soldier/machete_hitwall2.wav
sound/snk_ema/soldier/machete_slash1.wav
sound/snk_ema/soldier/machete_slash2.wav
sound/snk_ema/soldier/machete_stab.wav
sound/snk_ema/soldier/machlow.wav
sound/snk_ema/soldier/mossberg_1.wav
sound/snk_ema/soldier/mossberg_2.wav
sound/snk_ema/soldier/P228-1.wav
sound/snk_ema/soldier/p228_clipin.wav
sound/snk_ema/soldier/p228_clipout.wav
sound/snk_ema/soldier/p228_slideback.wav
sound/snk_ema/soldier/p228_slideforward.wav
sound/snk_ema/soldier/p228_sliderelease.wav
sound/snk_ema/soldier/phone0.wav
sound/snk_ema/soldier/phone3.wav
sound/snk_ema/soldier/pl_slosh1.wav
sound/snk_ema/soldier/pl_slosh2.wav
sound/snk_ema/soldier/pl_slosh3.wav
sound/snk_ema/soldier/pl_slosh4.wav
sound/snk_ema/soldier/reload1.wav
sound/snk_ema/soldier/scock1.wav
sound/snk_ema/soldier/tmp_boltpull.wav
sound/snk_ema/soldier/tmp_boltslap.wav
sound/snk_ema/soldier/tmp_clipin.wav
sound/snk_ema/soldier/tmp_clipout.wav
sound/snk_ema/soldier/tmp_switch.wav
sound/snk_ema/soldier/wind1.wav
sound/weapons/pinpull.wav
sound/weapons/weapon_holster.wav
sprites/custom_weapons/opfor/640hud7.spr
sprites/custom_weapons/opfor/640hudof03.spr
sprites/custom_weapons/opfor/640hudof04.spr
sprites/custom_weapons/opfor/ofch1.spr
sprites/custom_weapons/opfor/weapon_op4_shockrifle.txt
sprites/fire1.spr
sprites/hl_weapons/weapon_hl357.txt
sprites/hl_weapons/weapon_hl9mmhandgun.txt
sprites/hl_weapons/weapon_hlcrossbow.txt
sprites/hl_weapons/weapon_hlgauss.txt
sprites/isc/sdx/weapon_sdx_welder.txt
sprites/ledanimate.spr
sprites/ledblue.spr
sprites/ledorange.spr
sprites/ledred.spr
